---
name: practical-05
break: true
indent: 4
---
src/main:
    java:
        gatorcash/BankAccount.java:
            ConfirmFileExists

src/main:
    java:
        gatorcash/Bill.java:
            ConfirmFileExists
            MatchFileFragment --fragment "= NumberFormat.getCurrencyInstance();" --count 1 --exact
            MatchFileRegex --regex "return\s[a-zA-Z0-9]+\.format\(amount\);" --count 1 --exact

src/main:
    java:
        gatorcash/GatorAccount.java:
            ConfirmFileExists
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "{Your Name Here}" --count 0 --exact
            MatchFileFragment --fragment "= new BankAccount(startingBalance);" --count 1 --exact
            MatchFileFragment --fragment "account.debit(" --count 1 --exact
            MatchFileFragment --fragment ".fmtAmount()" --count 1 --exact
            MatchFileFragment --fragment ".getBalance()" --count 1 --exact
            MatchFileRegex --regex "=\snew Bill\(payee,(\s)?amount,(\s)?date\);" --count 1 --exact

ExecuteCommand --command "gradle build"
MatchCommandRegex --command "gradle run --args='18.48'" --regex "(-)?(\()?\$[0-9]+\.[0-9]{2}(\))?" --count 2 --exact
MatchCommandRegex --command "gradle run --args='18.48'" --regex "Wiz Hats Unlimited" --count 1 --exact  
